# Generated by Django 4.0.1 on 2022-02-15 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0002_alter_comment_body_alter_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='favorite_place',
            field=models.CharField(blank=True, help_text='Optional', max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='visited_places',
            field=models.CharField(blank=True, help_text='Optional', max_length=100),
        ),
    ]
